In [1]:
import numpy as np


In [2]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([2, 4, 6, 8, 10])

In [3]:
addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2 
power = arr1 ** arr2

print("\nAddition:", addition)
print("Multiplication:", multiplication)
print("Subtraction:", subtraction)
print("Division:", division)
print("Power:", power)



Addition: [12 24 36 48 60]
Multiplication: [ 20  80 180 320 500]
Subtraction: [ 8 16 24 32 40]
Division: [5. 5. 5. 5. 5.]
Power: [        100      160000   729000000  -520093696 -1957116928]


In [5]:
import pandas as pd
# code by Krish

data1 = {
    'ID': [1, 2, 3],
    'Name': ['Rohan', 'Krish', 'Animesh']
}
df1 = pd.DataFrame(data1)

data2 = {
    'ID': [4, 5, 6],
    'Name': ['Ahan', 'Priya', 'Faruk']
}
df2 = pd.DataFrame(data2)

result = pd.concat([df1, df2], ignore_index=True)

print("Concatenated DataFrame:")
print(result)



Concatenated DataFrame:
   ID     Name
0   1    Rohan
1   2    Krish
2   3  Animesh
3   4     Ahan
4   5    Priya
5   6    Faruk


In [8]:
import os
# code by Krish

def check_file(filename):
    if os.path.exists(filename):
        print(f"File '{filename}' already exists.")
    else:
        print(f"File '{filename}' not found. Creating with demo data...")
        with open(filename, 'w') as f:
            f.write("Today i am very sad because\ni lost my key chain when visit my\nown greenhouse in ranch simulator game, now i can't find it\nand notable to use my truck to pick maximum wood planks.\n")
        print(f"File '{filename}' created successfully.")


def file_calc(filename):
    check_file(filename)
    with open(filename, 'r') as f:
        text = f.read()

    num_chars = len(text)
    num_words = len(text.split())
    num_lines = len(text.splitlines())

    print("Number of characters:", num_chars)
    print("Number of words:", num_words)
    print("Number of lines:", num_lines)

file_calc("this.txt")

File 'this.txt' not found. Creating with demo data...
File 'this.txt' created successfully.
Number of characters: 179
Number of words: 36
Number of lines: 4


In [9]:
import numpy as np
# code by Krish

n = 4
matrix = np.zeros((n, n), dtype=int)

for i in range(n):
    for j in range(n):
        matrix[i][j] = (i + j) % 2

print(matrix)


[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [10]:
import csv
# code by Krish 

data = [["Name", "Age"], ["Tom", 32], ["Jerry", 22]]

with open("this.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(data)

print("Data written to this.csv")


Data written to this.csv


In [11]:
# code by Krish
def linear_search(arr, target):
    for i in range(len(arr)):
        if arr[i] == target:
            return i
    return -1

def binary_search(arr, target):
    low, high = 0, len(arr) - 1
    while low <= high:
        mid = (low + high) // 2
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            low = mid + 1
        else:
            high = mid - 1
    return -1

arr = [1, 3, 5, 7, 9]
print("Linear Search:", linear_search(arr, 7))
print("Binary Search:", binary_search(arr, 7))


Linear Search: 3
Binary Search: 3


In [ ]:
# code by Krish
A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Addition:\n", A + B)
print("Subtraction:\n", A - B)
print("Division:\n", A / B)
print("Power:\n", np.power(A, 2))


Matrix A:
 [[6 3 4]
 [3 5 5]
 [9 6 6]]
Matrix B:
 [[1 4 2]
 [7 1 9]
 [1 6 1]]
Addition:
 [[ 7  7  6]
 [10  6 14]
 [10 12  7]]
Subtraction:
 [[ 5 -1  2]
 [-4  4 -4]
 [ 8  0  5]]
Division:
 [[6.         0.75       2.        ]
 [0.42857143 5.         0.55555556]
 [9.         1.         6.        ]]
Power:
 [[36  9 16]
 [ 9 25 25]
 [81 36 36]]


In [14]:
from collections import deque
# code by Krish
def print_state(state):
    for i in range(0, 9, 3):
        print(state[i:i+3])
    print()

def get_neighbors(state):
    neighbors = []
    idx = state.index(0)
    row, col = divmod(idx, 3)

    moves = [(-1,0), (1,0), (0,-1), (0,1)]
    for dr, dc in moves:
        new_row, new_col = row + dr, col + dc
        if 0 <= new_row < 3 and 0 <= new_col < 3:
            new_idx = new_row * 3 + new_col
            new_state = list(state)
            new_state[idx], new_state[new_idx] = new_state[new_idx], new_state[idx]
            neighbors.append(tuple(new_state))
    return neighbors

def bfs(start, goal):
    queue = deque([(start, [])])
    visited = set([start])

    while queue:
        state, path = queue.popleft()
        if state == goal:
            return path + [state]

        for neighbor in get_neighbors(state):
            if neighbor not in visited:
                visited.add(neighbor)
                queue.append((neighbor, path + [state]))
    return None

print("Enter the start state (use 0 for empty tile):")
start_state = tuple(map(int, input().split()))

print("Enter the goal state (use 0 for empty tile):")
goal_state = tuple(map(int, input().split()))

solution = bfs(start_state, goal_state)

if solution:
    print("Solution found in", len(solution)-1, "moves:")
    for step in solution:
        print_state(step)
else:
    print("No solution exists.")


Enter the start state (use 0 for empty tile):
Enter the goal state (use 0 for empty tile):
Solution found in 14 moves:
(1, 2, 3)
(4, 0, 5)
(6, 7, 8)

(1, 2, 3)
(4, 5, 0)
(6, 7, 8)

(1, 2, 3)
(4, 5, 8)
(6, 7, 0)

(1, 2, 3)
(4, 5, 8)
(6, 0, 7)

(1, 2, 3)
(4, 5, 8)
(0, 6, 7)

(1, 2, 3)
(0, 5, 8)
(4, 6, 7)

(1, 2, 3)
(5, 0, 8)
(4, 6, 7)

(1, 2, 3)
(5, 6, 8)
(4, 0, 7)

(1, 2, 3)
(5, 6, 8)
(4, 7, 0)

(1, 2, 3)
(5, 6, 0)
(4, 7, 8)

(1, 2, 3)
(5, 0, 6)
(4, 7, 8)

(1, 2, 3)
(0, 5, 6)
(4, 7, 8)

(1, 2, 3)
(4, 5, 6)
(0, 7, 8)

(1, 2, 3)
(4, 5, 6)
(7, 0, 8)

(1, 2, 3)
(4, 5, 6)
(7, 8, 0)



In [2]:
n = int(input("Enter number of nodes: "))

adj_matrix = [[0 for _ in range(n)] for _ in range(n)]

m = int(input("Enter number of edges: "))

print("Enter each edge in format: u v c")
print("Where u = from node, v = to node, c = cost")

for _ in range(m):
    u, v, c = map(int, input().split())
    adj_matrix[u][v] = c

print("\nAdjacency Matrix:")
for row in adj_matrix:
    print(row)

Enter each edge in format: u v c
Where u = from node, v = to node, c = cost

Adjacency Matrix:
[0, 10, 3, 0, 0]
[0, 0, 1, 2, 0]
[0, 0, 0, 0, 2]
[0, 0, 0, 0, 7]
[0, 0, 0, 0, 0]


In [ ]:
# import heapq


# def build_adj_matrix():
#     n = int(input("Enter number of nodes: "))

#     adj_matrix = [[0 for _ in range(n)] for _ in range(n)]

#     m = int(input("Enter number of edges: "))

#     print("Enter each edge in format: u v c")
#     print("Where u = from node, v = to node, c = cost")

#     for _ in range(m):
#         u, v, c = map(int, input().split())
#         adj_matrix[u][v] = c

#     return adj_matrix


# def heuristic(a, b):
#     # return abs(a[0]- b[0]) + abs(a[1] - b[1])
#     return 0 # i am consider it 0



# def a_star(adj_matrix, start, goal):
#     n = len(adj_matrix)
#     open_set = []
#     heapq.heappush(open_set, (0, start))

#     came_from = {}
#     g_score = [float("inf")] * n
#     g_score[start] = 0

#     f_score = [float("inf")] * n
#     f_score[start] = heuristic(start, goal)

#     while open_set:
#         _, current = heapq.heappop(open_set)
#         if current == goal:
#             path = []
#             while current in came_from:
#                 path.append(current)
#                 current = came_from[current]
#             path.append(start)
#             path.reverse()
#             return path, g_score[goal]

#         for neighbor in range(n):
#             cost = adj_matrix[current][neighbor]
#             if cost > 0:
#                 tentative_g = g_score[current] + cost
#                 if tentative_g < g_score[neighbor]:
#                     came_from[neighbor] = current
#                     g_score[neighbor] = tentative_g
#                     f_score[neighbor] = tentative_g + heuristic(neighbor, goal)
#                     heapq.heappush(open_set, (f_score[neighbor], neighbor))

#     return None, float("inf")

# def main():
#     adj_matrix = build_adj_matrix()

#     print("\nAdjacency Matrix:")
#     for row in adj_matrix:
#         print(row)

#     start = int(input("\nEnter start node: "))
#     goal = int(input("Enter goal node: "))

#     path, cost = a_star(adj_matrix, start, goal)

#     if path:
#         print(f"\nShortest path from {start} to {goal}: {path}")
#         print(f"Total cost: {cost}")
#     else:
#         print("\nNo path found.")

# main()

Enter each edge in format: u v c
Where u = from node, v = to node, c = cost

Adjacency Matrix:
[0, 5, 6, 0, 0]
[0, 0, 0, 2, 0]
[0, 0, 0, 0, 4]
[0, 0, 0, 0, 1]
[0, 0, 0, 0, 0]

Shortest path from 0 to 4: [0, 1, 3, 4]
Total cost: 8


In [ ]:
import heapq

def build_adj_matrix():
    n = int(input("Enter the number of node: "))
    print("Number of node is ", n)

    adj_matrix = [[0 for _ in range(n)] for _ in range(n)]

    e = int(input("Enter the number of edge: "))
    print("Number of edge is ", e)

    print("Enter the egde in format: u v c")
    print("Where u = from node, v = to node, c = cost")

    try:
        for _ in range(e):
            u, v, c = map(int, input().split())
            adj_matrix[u][v] = c

        return adj_matrix

    except Exception as e:
        print(">> Input not satishfy the formt", e)
        return [[]]

def heuristic(a, b):
    return 0

def a_start_algo(adj_matrix, start, goal):
    n = len(adj_matrix)
    open_set = []
    heapq.heappush(open_set, (0, start))

    came_from = {}
    g_score = [float("inf")] * n
    g_score[start] = 0
    f_score = [float("inf")] * n
    f_score[start] = heuristic(start, goal)

    while open_set:
        _, current = heapq.heappop(open_set)
        if current == goal:
            path = []
            while current in came_from:
                path.append(current)
                current = came_from[current]
            path.append(start)
            path.reverse()
            return path, g_score[goal]

        for neighbor in range(n):
            cost = adj_matrix[current][neighbor]
            if cost > 0:
                tentative_g = g_score[current] + cost
                if tentative_g < g_score[neighbor]:
                    came_from[neighbor] = current
                    g_score[neighbor] = tentative_g
                    f_score[neighbor] = tentative_g + heuristic(neighbor, goal)
                    heapq.heappush(open_set, (f_score[neighbor], neighbor))
    
    return None, float("inf")

def main():
    adj_matrix = build_adj_matrix()

    print("Adj_Matrix is: ")
    for row in adj_matrix:
        print(row)

    start = int(input("Enter the start node: "))
    goal = int(input("Enter the goal node: "))

    print(f"Start node is {start}, goal node is {goal}")

    path, cost = a_start_algo(adj_matrix, start, goal)

    if path:
        print(f"Shortest path from {start} to {goal} is: {path}")
        print(f"In the cost of {cost}")
    else:
        print("Not found any path, please check your input!!!")


main()

In [ ]:
def ana_para(paragraph):
    vowels = "aeiou"+"AEIOU"
    vowel_count = 0
    consonant_count = 0
    digit_count = 0
    space_count = 0

    for char in paragraph:
        if char.isdigit():
            digit_count += 1
        elif char.isspace():
            space_count += 1
        elif char.isalpha():
            if char in vowels:
                vowel_count += 1
            else:
                consonant_count += 1

    print("Vowels:", vowel_count)
    print("Consonants:", consonant_count)
    print("Digits:", digit_count)
    print("Spaces:", space_count)
    
    words = paragraph.split()

    longest_word = max(words, key=len)
    print("Longest word:", longest_word)

    shortest_word = min(words, key=len)
    print("Shortest word:", shortest_word)

    reversed_sentence = paragraph[::-1]
    print("Reversed sentence:", reversed_sentence)

def main():
    paragraph = input("Enter a paragraph: ")
    ana_para(paragraph)

main()

In [ ]:
def calculate_grade(avg):
    if avg >= 90:
        return "O"
    elif avg >= 80:
        return "E"
    elif avg >= 70:
        return "A"
    elif avg >= 60:
        return "B"
    elif avg >= 50:
        return "C"
    elif avg >= 40:
        return "D"
    elif avg < 40:
        return "F"
    else:
        return "I" #incomplete according to makaut

N = int(input("Enter the number of students: "))

students = []  

for i in range(N):
    print(f"\nEnter marks for Student {i+1}:")
    name = input("Name: ")
    marks = []
    subject = ["DSA", "AI", "Cloud"]
    for j in range(3):
        m = int(input(f"{subject[j]} Subject marks: "))
        marks.append(m)

    total = sum(marks)
    avg = total / 3
    grade = calculate_grade(avg)

    students.append({
        "name": name,
        "marks": marks,
        "total": total,
        "average": avg,
        "grade": grade
    })

print("\n\t---------------- Student Results ----------------")
for s in students:
    print(f"Name: {s['name']}, Total: {s['total']}, Average: {s['average']:.2f}, Grade: {s['grade']}")

topper = max(students, key=lambda x: x["total"])
print(f"\nTopper: {topper['name']} with {topper['total']} marks")

class_avg = sum(s["average"] for s in students) / N
print(f"Class Average: {class_avg:.2f}")


In [ ]:
import random
# code by Krish

class Book:
    def __init__(self, book_id, title, author, available=True):
        self.book_id = book_id
        self.title = title
        self.author = author
        self.available = available

    def __str__(self):
        status = "Available" if self.available else "Not Available"
        return f"ID: {self.book_id}, Title: {self.title}, Author: {self.author}, Status: {status}"

class Library:
    def __init__(self):
        self.books = []

    def generate_id(self): 
        existing_ids = {book.book_id for book in self.books} 
        while True: 
            new_id = random.randint(1, 999999) 
            if new_id not in existing_ids: 
                return new_id

    def add_book(self, book): 
        existing_ids = {b.book_id for b in self.books} 
        if book.book_id in existing_ids: 
            book.book_id = self.generate_id() 
        self.books.append(book) 
        if book.book_id > 10:
            print(f"Book '{book.title}' added successfully with ID {book.book_id}.")

    def issue_book(self, book_id):
        for book in self.books:
            if book.book_id == book_id:
                if book.available:
                    book.available = False
                    print(f"Book '{book.title}' issued successfully.")
                else:
                    print(f"Book '{book.title}' is already issued.")
                return
        print("Book not found, Please check your input!")

    def return_book(self, book_id):
        for book in self.books:
            if book.book_id == book_id:
                if not book.available:
                    book.available = True
                    print(f"Book '{book.title}' returned successfully.")
                else:
                    print(f"Book '{book.title}' was not issued.")
                return
        print("Book not found. Maybe it is a false return!")

    def display_available_books(self):
        print("\nAvailable Books:")
        found = False
        for book in self.books:
            if book.available:
                print(book)
                found = True
        if not found:
            print("No books available, try to donate some books!")

    def search_by_title(self, title):
        for book in self.books:
            if book.title.lower() == title.lower():
                print(book)
                return
        print("Book not found. Please check your input!")


def main():
    library = Library()

    library.add_book(Book(1, "Can Machine Think Somthing New, The Rise of Autonomus Intelligence", "Krishnendu Mitra"))
    library.add_book(Book(2, "Data Structures with C", "Jane Smith"))
    library.add_book(Book(3, "Algorithms and Analysis", "Robert Brown"))
    library.add_book(Book(4, "Machine Learning with Coffee", "Andrew Ng"))
    library.add_book(Book(5, "Deep Learning and Core of Intelligence", "Ian Goodfellow"))
    library.add_book(Book(6, "Artificial Intelligence", "Stuart Russell"))
    library.add_book(Book(7, "Computer Networks", "James Kurose"))
    library.add_book(Book(8, "Operating Systems", "Abraham Silberschatz"))
    library.add_book(Book(9, "Data Structures with C", "W. Goddfrede"))
    library.add_book(Book(10, "Software Engineering", "Ian Sommerville"))

    print("Welcome to RCCIIT Library, Please choose your option")
    print("\n----- Library Menu -----")
    print("1. Add a new book")
    print("2. Issue a book")
    print("3. Return a book")
    print("4. Display all available books")
    print("5. Search book by title")
    print("Type 'exit' to quit")
    
    while True:
        choice = input("\nEnter your choice: ")

        if choice.lower() == "exit":
            print("Exiting Library System. Goodbye!")
            break

        elif choice == "1":
            try:
                book_id = 1000 #int(input("Enter Book ID: "))
                title = input("Enter Title: ")
                author = input("Enter Author: ")
                library.add_book(Book(book_id, title, author))
            except ValueError:
                print("Invalid input. Book ID must be a number.")

        elif choice == "2":
            try:
                book_id = int(input("Enter Book ID to issue: "))
                library.issue_book(book_id)
            except ValueError:
                print("Invalid input. Book ID must be a number.")

        elif choice == "3":
            try:
                book_id = int(input("Enter Book ID to return: "))
                library.return_book(book_id)
            except ValueError:
                print("Invalid input. Book ID must be a number.")

        elif choice == "4":
            library.display_available_books()

        elif choice == "5":
            title = input("Enter Title to search: ")
            library.search_by_title(title)

        else:
            print("Invalid choice. Please try again.")


if __name__ == "__main__":
    main()


In [4]:
#code by Krish
def tower_of_hanoi(n, source, target, auxiliary):
    if n == 1:
        print(f"Move disk 1 from {source} to {target}")
        return
    tower_of_hanoi (n-1, source, auxiliary, target)
    print(f"Move disk {n} from {source} to {target}")
    tower_of_hanoi(n-1, auxiliary, target, source)

n = int(input("Enter number of disks: "))
tower_of_hanoi(n, 'A', 'C', 'B')

Move disk 1 from A to C
Move disk 2 from A to B
Move disk 1 from C to B
Move disk 3 from A to C
Move disk 1 from B to A
Move disk 2 from B to C
Move disk 1 from A to C


In [ ]:
#bfs
from collections import deque

def build_adj_matrix():
    n = int(input("Enter the number of nodes: "))
    print(f"Number of nodes: {n}")

    e = int(input("Enter the number of edge: "))
    print(f"Number of edge: {e}")

    adj_matrix = [[] for _ in range(n+1)]

    print("Enter the edgs connection as formate of: u v")
    print("Where u = from node, v = to node")
    for _ in range(e):
        u, v = map(int, input().split())
        adj_matrix[u].append(v)
        adj_matrix[v].append(u)
    return adj_matrix

def bfs(adj_matrix, start):
    n = len(adj_matrix)
    visited = [0] * (n+1)
    queue = deque()
    queue.append(start)
    visited[start] = 1

    print("BFS Traversal: ")
    while queue:
        node = queue.popleft()
        print(f"{node} ", end="")

        for neighbor in adj_matrix[node]:
            if visited[neighbor] == 0:
                visited[neighbor] = 1
                queue.append(neighbor)
    print()

def main():
    adj_matrix = build_adj_matrix()
    start = int(input("Enter the start node: "))
    print(f"Start node is: {start}")

    bfs(adj_matrix, start)

main()

In [ ]:
#dfs
def build_adj_matrix():
    n = int(input("Enter the number of nodes: "))
    print(f"Number of nodes: {n}")
    e = int(input("Enter the number of edge: "))
    print(f"Number of edge: {e}")

    adj_matrix = [[] for _ in range(n+1)]

    print("Enter the edge connection as formate of: u v")
    print("Where u = from node, v = to node")
    for _ in range(e):
        u, v = map(int, input().split())
        adj_matrix[u].append(v)
        adj_matrix[v].append(u)
    return adj_matrix

def dfs_util(adj_matrix, node, visited):
    visited[node] = 1
    print(f"{node} ", end="")

    for neighbor in adj_matrix[node]:
        if visited[neighbor] == 0:
            dfs_util(adj_matrix, neighbor, visited)

def dfs(adj_matrix, start):
    n = len(adj_matrix)
    visited = [0] * (n+1)
    print("DFS Traversal: ", end="")
    dfs_util(adj_matrix, start, visited)
    print()

def main():
    adj_matrix = build_adj_matrix()

    print("Adj_Matrix is: ", adj_matrix)

    start = int(input("Enter the start node: "))
    print(f"Start node is: {start}")

    dfs(adj_matrix, start)

main()

In [ ]:
# Water jug
def print_step(path):
    print("Steps to reach the target: ")
    for step in path:
        print(step)
    print()

def water_jug(jug1, jug2, target):
    visited = set()
    queue = deque()

    queue.append(((0,0), []))

    while queue:
        (a, b), path = queue.popleft()
        if a == target and b == target:
            path.append((a, b))
            print_step(path)
            return True
        if (a, b) in visited:
            continue
        visited.add((a, b))
        moves = []
        moves.append((jug1, b))
        moves.append((a, jug2))
        moves.append((0, b))
        moves.append((a, 0))
        pour = min(a, jug2 - b)
        moves.append((a - pour, b + pour))
        pour = min(b, jug1 - a)
        moves.append((a + pour, b - pour))
        for state in moves:
            if state not in visited:
                queue.append((state, path + [(a, b)]))
    print("No solution found!")
    return False

def main():
    jug1 = int(input("Enter the capacity of jug1: "))
    jug2 = int(input("Enter the capcacity of jug2: "))
    target = int(input("Enter the target amount: "))

    water_jug(jug1, jug2, target)

main()

In [ ]:
import random
# code by Krish
def print_board(board):
    for row in board:
        print(" | ".join(row))
    print("-" * 9)

def generate_winning_positions(n=3):
    positions = []
    for r in range(n):
        positions.append([(r, c) for c in range(n)])
    for c in range(n):
        positions.append([(r, c) for r in range(n)])
    positions.append([(i, i) for i in range(n)])
    positions.append([(i, n - 1 - i) for i in range(n)])
    return positions

def check_winner(board, symbol):
    winning_positions = generate_winning_positions()
    for positions in winning_positions:
        if all(board[r][c] == symbol for r, c in positions):
            return positions
    return None

def is_draw(board):
    return all(cell != '.' for row in board for cell in row)

def ai_move(board, ai_symbol, human_symbol):
    for r in range(3):
        for c in range(3):
            if board[r][c] == '.':
                board[r][c] = ai_symbol
                if check_winner(board, ai_symbol):
                    return r, c
                board[r][c] = '.'

    for r in range(3):
        for c in range(3):
            if board[r][c] == '.':
                board[r][c] = human_symbol
                if check_winner(board, human_symbol):
                    board[r][c] = ai_symbol
                    return r, c
                board[r][c] = '.'

    if board[1][1] == '.':
        board[1][1] = ai_symbol
        return 1, 1

    for r, c in [(0,0),(0,2),(2,0),(2,2)]:
        if board[r][c] == '.':
            board[r][c] = ai_symbol
            return r, c

    free_cells = [(r,c) for r in range(3) for c in range(3) if board[r][c] == '.']
    r, c = random.choice(free_cells)
    board[r][c] = ai_symbol
    return r, c

def tic_tac_toe():
    board = [['.' for _ in range(3)] for _ in range(3)]

    mode = input("\tPlay as \n-----------------------\nPlayer 1 (vs AI) or \nPlayer 2 (vs Human)? \nEnter 1 or 2: ")

    if mode == '1':
        players = [('Human', 'O'), ('AI', 'X')]
    else:
        players = [('Player 1', 'O'), ('Player 2', 'X')]

    turn = 0

    while True:
        print_board(board)
        player, symbol = players[turn]
        print(f"{player}'s turn ({symbol})")

        if player == "AI":
            row, col = ai_move(board, symbol, players[0][1])
            print(f"AI chooses: {row}, {col}")
        else:
            try:
                row = int(input("Enter row (0-2): "))
                col = int(input("Enter col (0-2): "))
            except ValueError:
                print("Invalid input! Please enter numbers 0, 1, or 2.")
                continue

            if 0 <= row < 3 and 0 <= col < 3 and board[row][col] == '.':
                board[row][col] = symbol
            else:
                print("Invalid move! Try again.")
                continue

        winning_positions = check_winner(board, symbol)
        if winning_positions:
            print_board(board)
            print(f"{player} wins! Winning positions: {winning_positions}")
            break

        if is_draw(board):
            print_board(board)
            print("It's a draw!")
            break

        turn = 1 - turn

if __name__ == "__main__":
    tic_tac_toe()